### PR TITLE
Bugfix: glMemoryBarrier() after draw/compute calls

### PR DESCRIPTION
**Pull request by w-flo**
Here's the first PR I promised. I hope I didn't miss any required glMemoryBarrier() spots.

### CODE REVIEW

**Comment by w-flo** [comment]
So the clang build fails:  error: use of undeclared identifier 'GL_ALL_BARRIER_BITS'

I'm not sure how to fix this and have no Apple hardware for testing, so I don't want to keep pushing fix attempts until clang likes it. :-) 

Maybe add
#ifdef GL_ARB_shader_image_load_store 
?

**Comment by w-flo** [comment]
I have a #ifdef GL_ARB_shader_image_load_store check ready to be pushed, but since I'm not sure if it's the right way to do the check (is a runtime check required? Should it check for either the extension, or OpenGL >= 4.2, or OpenGL ES >= 3.1, since all three variants support memory barriers?) I'm waiting for comments about this.

**Comment by BearishSun** [comment]
Yep I believe you figured it out, adding `#if BS_OPENGL_4_2 || BS_OPENGLES_3_1` should be the right call. Other than that, everything looks good.

**Comment by BearishSun** [comment]
Merged, thanks!

**Pull request merged**
