### PR TITLE
Fix whitespace and newlines

### PR DESCRIPTION
**Pull request by pgruenbacher**
updated .editorconfig so this issues is fixed in the future.
otherwise just updates all files to not have trailing whitespace or missing newlines at end of file.
https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

### CODE REVIEW

**Comment by BearishSun** [comment]
Thanks, it's nice to have this standardized. 

I'm seeing additions of 1 byte to binary files, such as .png, .ttf and others. Can you avoid updating those?

**Comment by pgruenbacher** [comment]
oops yea you're right.

**Comment by pgruenbacher** [comment]
ok if you look at the file filter now, you should see that only text file extensions have been updated now.

**Comment by BearishSun** [comment]
Thanks, merged.

**Pull request closed without merging**
