### PR TITLE
Bugfix: Problem with basic shadow setups with radial or spot light (#168)

### PR DESCRIPTION
**Pull request by ivalduan**
The problem with radial lights was related with the ordering of the planes as you guessed.

The problem with spot lights is a problem with matrix transforms, there is some computations that I am not grasping completely, but the bug seems to be fixed by getting the correct worldMatrix, seems that previous approach was as the transpose of view, but view is not orthogonal so this is not equivalent to the inverse.

### CODE REVIEW

**Comment by BearishSun** [comment]
Thanks for taking the time to track it down, as well as providing reproducible test case!

I wasn't able to merge your PR directly because I guess it diverged too much from upstream. git just wasn't able to figure it out - rebase just plain skipped one of the commits and merge introduced changes that were already part of the branch for about 40 files.

So in the end I just made the changes manually. ea7332a65ab13eca3225755454bb840e8a2075ee

**Comment by ivalduan** [comment]
Hmm weird, I merged the current state of upstream to my fork before PR.

Just out of curiosity, what is the recommended way of handling small PRs with github?
I thought having a sync fork was the only way but maybe it is better to open a new branch per each PR from the most recent upstream/master commit and then closing it.

**Comment by BearishSun** [comment]
Not really sure what confused git, when I did a merge it did a fast-forward and if everything seemed fine, but when I looked one of the commits it contained a bunch of changes from previous commits that were already part of that branch.

I think the cleanest way is to open up a new branch for each PR as you suggested.

**Comment by jonesmz** [comment]
What I always do is
1) Make sure my "master" branch is always identical to upstream.
2) For any feature branches that I'm creating, if I update my master branch, i "git rebase" my feature branch so that it's always adding my commits on top of what's in the master branch, and the git log shows a direct linear relationship instead of a fork.

It's more work, but I've had github's PR interface screw things up frequently, and git itself has trouble with merging frequently enough, that I think it's about break even as far as paying the effort ahead of time or after the fact.

**Pull request closed without merging**
